entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https

  websecure:
    address: ":443"

  dashboard:
    address: ":9090"

api:
  dashboard: true
  insecure: true

providers:
  file:
    directory: ./config
    watch: true

log:
  level: INFO

